---
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/crazy_task_traker
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


